version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: ejs
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: js-yaml
    versions:
    - 4.0.0
